export const SCRIPT_REVISION_QUICK_FIXES = {
  MAKE_SHORTER: "make_shorter",
  MORE_SAUDI_DIALECT: "more_saudi_dialect",
  LESS_FORMAL: "less_formal",
  STRONGER_HOOK: "stronger_hook",
  MORE_FUNNY: "more_funny",
  MORE_PREMIUM: "more_premium",
  LESS_SHOT_DIRECTIONS: "less_shot_directions",
  ONE_NARRATOR_ONLY: "one_narrator_only",
} as const;

export const SCRIPT_REVISION_QUICK_FIX_VALUES = [
  SCRIPT_REVISION_QUICK_FIXES.MAKE_SHORTER,
  SCRIPT_REVISION_QUICK_FIXES.MORE_SAUDI_DIALECT,
  SCRIPT_REVISION_QUICK_FIXES.LESS_FORMAL,
  SCRIPT_REVISION_QUICK_FIXES.STRONGER_HOOK,
  SCRIPT_REVISION_QUICK_FIXES.MORE_FUNNY,
  SCRIPT_REVISION_QUICK_FIXES.MORE_PREMIUM,
  SCRIPT_REVISION_QUICK_FIXES.LESS_SHOT_DIRECTIONS,
  SCRIPT_REVISION_QUICK_FIXES.ONE_NARRATOR_ONLY,
] as const;

export const SCRIPT_REVISION_LIMITS = {
  CURRENT_SCRIPT_MAX: 20000,
  REVISION_NOTES_MAX: 4000,
  REVISED_SCRIPT_MAX: 20000,
} as const;
