export const ROUTES = {
  LOGIN: "/login",
  TODAY: "/today",
  CALENDAR: "/calendar",
  CALENDAR_WEEKLY: "/calendar/week",
  MARKETING_CALENDAR: "/marketing-calendar",
  TOPICS: "/topics",
  CAMPAIGNS: "/campaigns",
  CAMPAIGN_DETAIL: (id: string) => `/campaigns/${id}`,
  INFLUENCERS: "/influencers",
  INFLUENCER_DETAIL: (id: string) => `/influencers/${id}`,
  INFLUENCER_VERIFICATIONS: "/influencers/verifications",
  CREATOR_PORTAL: (token: string) => `/creator/${token}`,
  PERFORMANCE: "/performance",
  BUDGET: "/budget",
  SETTINGS: "/settings",
} as const;
